In [41]:
import tensorflow as tf
# 创建变量
# tf.random_normal 方法返回形状为(1，4)的张量。它的4个元素符合均值为100、标准差为0.35的正态分布。
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35), name="W")
b = tf.Variable(tf.zeros([4]), name="b")

# 指定需要保存和恢复的变量
saver = tf.train.Saver({'v1': W, 'v2': b})
[W, b]

[<tf.Variable 'W_4:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b_4:0' shape=(4,) dtype=float32_ref>]

In [42]:
# 初始化变量
# 创建会话（之后小节介绍）
sess = tf.Session()
# 使用 global_variables_initializer 方法初始化全局变量 W 和 b
sess.run(tf.global_variables_initializer())
# 执行操作，获取变量值
sess.run([W, b])

[array([[100.1806  ,  99.878975,  99.91918 , 100.18799 ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [43]:
# 执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))

array([1., 1., 1., 1.], dtype=float32)

In [45]:
# 查看变量 b 是否更新成功
sess.run(b)

array([1., 1., 1., 1.], dtype=float32)

In [46]:
import os
saved_file = saver.save(sess, os.path.realpath('my-model'), global_step=0) # ==> filename: 'my-model-0'

In [47]:
with tf.Session() as sess:
    saver.restore(sess, saved_file)
    print("Model restored.")
    # Check the values of the variables
    print("v1 : %s" % W.eval())
    print("v2 : %s" % b.eval())

#

INFO:tensorflow:Restoring parameters from /home/mio/PycharmProjects/tf/tensorflow-101-master/notebook-examples/chapter-3/my-model-0
Model restored.
v1 : [[100.1806    99.878975  99.91918  100.18799 ]]
v2 : [1. 1. 1. 1.]


INFO:tensorflow:Restoring parameters from /home/mio/PycharmProjects/tf/tensorflow-101-master/notebook-examples/chapter-3/my-model-0


### Saver 使用示例

In [17]:
v1 = tf.Variable(W, name='v1')
v2 = tf.Variable(b, name='v2')
# 指定需要保存和恢复的变量
saver = tf.train.Saver({'v1': v1, 'v2': v2})
saver = tf.train.Saver([v1, v2])
saver = tf.train.Saver({v.op.name: v for v in [v1, v2]})
# 保存变量的方法
import os
saver.save(sess, os.path.realpath('my-model'), global_step=0) # ==> filename: 'my-model-0'
#```

FailedPreconditionError: Attempting to use uninitialized value v1_9
	 [[node save_20/SaveV2 (defined at <ipython-input-17-dc53b2e802bb>:6) ]]

Caused by op 'save_20/SaveV2', defined at:
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/mio/tf/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/home/mio/tf/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/mio/tf/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/mio/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/mio/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/mio/tf/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/mio/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/mio/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/mio/tf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-dc53b2e802bb>", line 6, in <module>
    saver = tf.train.Saver({v.op.name: v for v in [v1, v2]})
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 510, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 210, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 124, in save_op
    tensors)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1807, in save_v2
    name=name)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/mio/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value v1_9
	 [[node save_20/SaveV2 (defined at <ipython-input-17-dc53b2e802bb>:6) ]]


In [53]:
# 创建Saver
# 创建会话（之后小节介绍）
sess = tf.Session()
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35), name="W")
b = tf.Variable(tf.zeros([4]), name="b")
saver = tf.train.Saver({'W': W, 'b': b})
sess.run(tf.global_variables_initializer())
# 执行操作，获取变量值
sess.run([W, b])
# 存储变量到文件 './summary/test.ckpt-0'
saver.save(sess, './summary/test.ckpt', global_step=0)

'./summary/test.ckpt-0'

In [54]:
# 再次执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))
# 获取变量 b 的最新值
sess.run(b)

array([1., 1., 1., 1.], dtype=float32)

In [55]:
# 从文件中恢复变量 b 的值
saver.restore(sess, './summary/test.ckpt-0')
# 查看变量 b 是否恢复成功
sess.run(b)

INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


array([0., 0., 0., 0.], dtype=float32)

In [ ]:
# 从文件中恢复数据流图结构
# tf.train.import_meta_graph